/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateSkuArgs } from "./CreateSkuArgs";
import { UpdateSkuArgs } from "./UpdateSkuArgs";
import { DeleteSkuArgs } from "./DeleteSkuArgs";
import { SkuFindManyArgs } from "./SkuFindManyArgs";
import { SkuFindUniqueArgs } from "./SkuFindUniqueArgs";
import { Sku } from "./Sku";
import { SkuPackageFindManyArgs } from "../../skuPackage/base/SkuPackageFindManyArgs";
import { SkuPackage } from "../../skuPackage/base/SkuPackage";
import { SkuService } from "../sku.service";

@graphql.Resolver(() => Sku)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class SkuResolverBase {
  constructor(
    protected readonly service: SkuService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Sku",
    action: "read",
    possession: "any",
  })
  async _skusMeta(
    @graphql.Args() args: SkuFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Sku])
  @nestAccessControl.UseRoles({
    resource: "Sku",
    action: "read",
    possession: "any",
  })
  async skus(@graphql.Args() args: SkuFindManyArgs): Promise<Sku[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Sku, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Sku",
    action: "read",
    possession: "own",
  })
  async sku(@graphql.Args() args: SkuFindUniqueArgs): Promise<Sku | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Sku)
  @nestAccessControl.UseRoles({
    resource: "Sku",
    action: "create",
    possession: "any",
  })
  async createSku(@graphql.Args() args: CreateSkuArgs): Promise<Sku> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        packages: args.data.packages
          ? {
              connect: args.data.packages,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Sku)
  @nestAccessControl.UseRoles({
    resource: "Sku",
    action: "update",
    possession: "any",
  })
  async updateSku(@graphql.Args() args: UpdateSkuArgs): Promise<Sku | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          packages: args.data.packages
            ? {
                connect: args.data.packages,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Sku)
  @nestAccessControl.UseRoles({
    resource: "Sku",
    action: "delete",
    possession: "any",
  })
  async deleteSku(@graphql.Args() args: DeleteSkuArgs): Promise<Sku | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [SkuPackage])
  @nestAccessControl.UseRoles({
    resource: "SkuPackage",
    action: "read",
    possession: "any",
  })
  async skuPackages(
    @graphql.Parent() parent: Sku,
    @graphql.Args() args: SkuPackageFindManyArgs
  ): Promise<SkuPackage[]> {
    const results = await this.service.findSkuPackages(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => SkuPackage, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SkuPackage",
    action: "read",
    possession: "any",
  })
  async packages(@graphql.Parent() parent: Sku): Promise<SkuPackage | null> {
    const result = await this.service.getPackages(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
