/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsJSON,
  IsOptional,
  ValidateNested,
  IsString,
  IsEnum,
} from "class-validator";
import { GraphQLJSONObject } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { MapSkusToPackageCreateNestedManyWithoutSkusInput } from "./MapSkusToPackageCreateNestedManyWithoutSkusInput";
import { Type } from "class-transformer";
import { SkuGroupWhereUniqueInput } from "../../skuGroup/base/SkuGroupWhereUniqueInput";
import { SkuSubGroupWhereUniqueInput } from "../../skuSubGroup/base/SkuSubGroupWhereUniqueInput";
import { EnumSkuSkuType } from "./EnumSkuSkuType";
@InputType()
class SkuCreateInput {
  @ApiProperty({
    required: false,
  })
  @IsJSON()
  @IsOptional()
  @Field(() => GraphQLJSONObject, {
    nullable: true,
  })
  fulfillmentInfo?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => MapSkusToPackageCreateNestedManyWithoutSkusInput,
  })
  @ValidateNested()
  @Type(() => MapSkusToPackageCreateNestedManyWithoutSkusInput)
  @IsOptional()
  @Field(() => MapSkusToPackageCreateNestedManyWithoutSkusInput, {
    nullable: true,
  })
  mapSkusToPackages?: MapSkusToPackageCreateNestedManyWithoutSkusInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  skuDescription?: string | null;

  @ApiProperty({
    required: false,
    type: () => SkuGroupWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SkuGroupWhereUniqueInput)
  @IsOptional()
  @Field(() => SkuGroupWhereUniqueInput, {
    nullable: true,
  })
  skuGroupId?: SkuGroupWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  skuName?: string | null;

  @ApiProperty({
    required: false,
    type: () => SkuSubGroupWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SkuSubGroupWhereUniqueInput)
  @IsOptional()
  @Field(() => SkuSubGroupWhereUniqueInput, {
    nullable: true,
  })
  skuSubGroupId?: SkuSubGroupWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    enum: EnumSkuSkuType,
  })
  @IsEnum(EnumSkuSkuType)
  @IsOptional()
  @Field(() => EnumSkuSkuType, {
    nullable: true,
  })
  skuType?: "Item" | "Package" | null;
}
export { SkuCreateInput };
