/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsJSON,
  IsOptional,
  ValidateNested,
  IsString,
  IsEnum,
} from "class-validator";
import { GraphQLJSONObject } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { SkuWhereUniqueInput } from "./SkuWhereUniqueInput";
import { Type } from "class-transformer";
import { SkuPackageUpdateManyWithoutSkusInput } from "./SkuPackageUpdateManyWithoutSkusInput";
import { SkuUpdateManyWithoutSkusInput } from "./SkuUpdateManyWithoutSkusInput";
import { EnumSkuSkuType } from "./EnumSkuSkuType";
@InputType()
class SkuUpdateInput {
  @ApiProperty({
    required: false,
  })
  @IsJSON()
  @IsOptional()
  @Field(() => GraphQLJSONObject, {
    nullable: true,
  })
  fulfillmentInfo?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => SkuWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SkuWhereUniqueInput)
  @IsOptional()
  @Field(() => SkuWhereUniqueInput, {
    nullable: true,
  })
  inclusions?: SkuWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  skuId?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  skuName?: string | null;

  @ApiProperty({
    required: false,
    type: () => SkuPackageUpdateManyWithoutSkusInput,
  })
  @ValidateNested()
  @Type(() => SkuPackageUpdateManyWithoutSkusInput)
  @IsOptional()
  @Field(() => SkuPackageUpdateManyWithoutSkusInput, {
    nullable: true,
  })
  skuPackages?: SkuPackageUpdateManyWithoutSkusInput;

  @ApiProperty({
    required: false,
    type: () => SkuUpdateManyWithoutSkusInput,
  })
  @ValidateNested()
  @Type(() => SkuUpdateManyWithoutSkusInput)
  @IsOptional()
  @Field(() => SkuUpdateManyWithoutSkusInput, {
    nullable: true,
  })
  skus?: SkuUpdateManyWithoutSkusInput;

  @ApiProperty({
    required: false,
    enum: EnumSkuSkuType,
  })
  @IsEnum(EnumSkuSkuType)
  @IsOptional()
  @Field(() => EnumSkuSkuType, {
    nullable: true,
  })
  skuType?: "Item" | "Package" | null;
}
export { SkuUpdateInput };
