/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { JsonFilter } from "../../util/JsonFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested, IsEnum } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { SkuPackageListRelationFilter } from "../../skuPackage/base/SkuPackageListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { SkuGroupWhereUniqueInput } from "../../skuGroup/base/SkuGroupWhereUniqueInput";
import { EnumSkuSkuType } from "./EnumSkuSkuType";
@InputType()
class SkuWhereInput {
  @ApiProperty({
    required: false,
    type: JsonFilter,
  })
  @Type(() => JsonFilter)
  @IsOptional()
  @Field(() => JsonFilter, {
    nullable: true,
  })
  fulfillmentInfo?: JsonFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => SkuPackageListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SkuPackageListRelationFilter)
  @IsOptional()
  @Field(() => SkuPackageListRelationFilter, {
    nullable: true,
  })
  inclusionSku?: SkuPackageListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  skuDescription?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => SkuGroupWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SkuGroupWhereUniqueInput)
  @IsOptional()
  @Field(() => SkuGroupWhereUniqueInput, {
    nullable: true,
  })
  skuGroupId?: SkuGroupWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  skuName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => SkuPackageListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SkuPackageListRelationFilter)
  @IsOptional()
  @Field(() => SkuPackageListRelationFilter, {
    nullable: true,
  })
  skuPackages?: SkuPackageListRelationFilter;

  @ApiProperty({
    required: false,
    enum: EnumSkuSkuType,
  })
  @IsEnum(EnumSkuSkuType)
  @IsOptional()
  @Field(() => EnumSkuSkuType, {
    nullable: true,
  })
  skuType?: "Item" | "Package";
}
export { SkuWhereInput };
