/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SkuGroupService } from "../skuGroup.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SkuGroupCreateInput } from "./SkuGroupCreateInput";
import { SkuGroupWhereInput } from "./SkuGroupWhereInput";
import { SkuGroupWhereUniqueInput } from "./SkuGroupWhereUniqueInput";
import { SkuGroupFindManyArgs } from "./SkuGroupFindManyArgs";
import { SkuGroupUpdateInput } from "./SkuGroupUpdateInput";
import { SkuGroup } from "./SkuGroup";
import { SkuFindManyArgs } from "../../sku/base/SkuFindManyArgs";
import { Sku } from "../../sku/base/Sku";
import { SkuWhereUniqueInput } from "../../sku/base/SkuWhereUniqueInput";
import { SkuSubGroupFindManyArgs } from "../../skuSubGroup/base/SkuSubGroupFindManyArgs";
import { SkuSubGroup } from "../../skuSubGroup/base/SkuSubGroup";
import { SkuSubGroupWhereUniqueInput } from "../../skuSubGroup/base/SkuSubGroupWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SkuGroupControllerBase {
  constructor(
    protected readonly service: SkuGroupService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "SkuGroup",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SkuGroup })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: SkuGroupCreateInput): Promise<SkuGroup> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        id: true,
        skuGroupName: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "SkuGroup",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [SkuGroup] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(SkuGroupFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<SkuGroup[]> {
    const args = plainToClass(SkuGroupFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        skuGroupName: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "SkuGroup",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SkuGroup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: SkuGroupWhereUniqueInput
  ): Promise<SkuGroup | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        skuGroupName: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "SkuGroup",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SkuGroup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: SkuGroupWhereUniqueInput,
    @common.Body() data: SkuGroupUpdateInput
  ): Promise<SkuGroup | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          skuGroupName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "SkuGroup",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SkuGroup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: SkuGroupWhereUniqueInput
  ): Promise<SkuGroup | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          skuGroupName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Sku",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/skus")
  @ApiNestedQuery(SkuFindManyArgs)
  async findManySkus(
    @common.Req() request: Request,
    @common.Param() params: SkuGroupWhereUniqueInput
  ): Promise<Sku[]> {
    const query = plainToClass(SkuFindManyArgs, request.query);
    const results = await this.service.findSkus(params.id, {
      ...query,
      select: {
        createdAt: true,
        fulfillmentInfo: true,
        id: true,
        skuDescription: true,

        skuGroupId: {
          select: {
            id: true,
          },
        },

        skuName: true,

        skuSubGroupId: {
          select: {
            id: true,
          },
        },

        skuType: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "SkuGroup",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/skus")
  async connectSkus(
    @common.Param() params: SkuGroupWhereUniqueInput,
    @common.Body() body: SkuWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      skus: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "SkuGroup",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/skus")
  async updateSkus(
    @common.Param() params: SkuGroupWhereUniqueInput,
    @common.Body() body: SkuWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      skus: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "SkuGroup",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/skus")
  async disconnectSkus(
    @common.Param() params: SkuGroupWhereUniqueInput,
    @common.Body() body: SkuWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      skus: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "SkuSubGroup",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/skuSubGroups")
  @ApiNestedQuery(SkuSubGroupFindManyArgs)
  async findManySkuSubGroups(
    @common.Req() request: Request,
    @common.Param() params: SkuGroupWhereUniqueInput
  ): Promise<SkuSubGroup[]> {
    const query = plainToClass(SkuSubGroupFindManyArgs, request.query);
    const results = await this.service.findSkuSubGroups(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        skuGroupId: {
          select: {
            id: true,
          },
        },

        skuSubGroupName: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "SkuGroup",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/skuSubGroups")
  async connectSkuSubGroups(
    @common.Param() params: SkuGroupWhereUniqueInput,
    @common.Body() body: SkuSubGroupWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      skuSubGroups: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "SkuGroup",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/skuSubGroups")
  async updateSkuSubGroups(
    @common.Param() params: SkuGroupWhereUniqueInput,
    @common.Body() body: SkuSubGroupWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      skuSubGroups: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "SkuGroup",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/skuSubGroups")
  async disconnectSkuSubGroups(
    @common.Param() params: SkuGroupWhereUniqueInput,
    @common.Body() body: SkuSubGroupWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      skuSubGroups: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
