/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SkuSubGroupIdService } from "../skuSubGroupId.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SkuSubGroupIdCreateInput } from "./SkuSubGroupIdCreateInput";
import { SkuSubGroupIdWhereInput } from "./SkuSubGroupIdWhereInput";
import { SkuSubGroupIdWhereUniqueInput } from "./SkuSubGroupIdWhereUniqueInput";
import { SkuSubGroupIdFindManyArgs } from "./SkuSubGroupIdFindManyArgs";
import { SkuSubGroupIdUpdateInput } from "./SkuSubGroupIdUpdateInput";
import { SkuSubGroupId } from "./SkuSubGroupId";
import { SkuFindManyArgs } from "../../sku/base/SkuFindManyArgs";
import { Sku } from "../../sku/base/Sku";
import { SkuWhereUniqueInput } from "../../sku/base/SkuWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SkuSubGroupIdControllerBase {
  constructor(
    protected readonly service: SkuSubGroupIdService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "SkuSubGroupId",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SkuSubGroupId })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: SkuSubGroupIdCreateInput
  ): Promise<SkuSubGroupId> {
    return await this.service.create({
      data: {
        ...data,

        skuGroupId: data.skuGroupId
          ? {
              connect: data.skuGroupId,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        skuGroupId: {
          select: {
            id: true,
          },
        },

        skuSubGroupName: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "SkuSubGroupId",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [SkuSubGroupId] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(SkuSubGroupIdFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<SkuSubGroupId[]> {
    const args = plainToClass(SkuSubGroupIdFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,

        skuGroupId: {
          select: {
            id: true,
          },
        },

        skuSubGroupName: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "SkuSubGroupId",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SkuSubGroupId })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: SkuSubGroupIdWhereUniqueInput
  ): Promise<SkuSubGroupId | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,

        skuGroupId: {
          select: {
            id: true,
          },
        },

        skuSubGroupName: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "SkuSubGroupId",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SkuSubGroupId })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: SkuSubGroupIdWhereUniqueInput,
    @common.Body() data: SkuSubGroupIdUpdateInput
  ): Promise<SkuSubGroupId | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          skuGroupId: data.skuGroupId
            ? {
                connect: data.skuGroupId,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          skuGroupId: {
            select: {
              id: true,
            },
          },

          skuSubGroupName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "SkuSubGroupId",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SkuSubGroupId })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: SkuSubGroupIdWhereUniqueInput
  ): Promise<SkuSubGroupId | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,

          skuGroupId: {
            select: {
              id: true,
            },
          },

          skuSubGroupName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Sku",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/skus")
  @ApiNestedQuery(SkuFindManyArgs)
  async findManySkus(
    @common.Req() request: Request,
    @common.Param() params: SkuSubGroupIdWhereUniqueInput
  ): Promise<Sku[]> {
    const query = plainToClass(SkuFindManyArgs, request.query);
    const results = await this.service.findSkus(params.id, {
      ...query,
      select: {
        createdAt: true,
        fulfillmentInfo: true,
        id: true,
        skuDescription: true,

        skuGroupId: {
          select: {
            id: true,
          },
        },

        skuName: true,

        skuSubGroupId: {
          select: {
            id: true,
          },
        },

        skuType: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "SkuSubGroupId",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/skus")
  async connectSkus(
    @common.Param() params: SkuSubGroupIdWhereUniqueInput,
    @common.Body() body: SkuWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      skus: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "SkuSubGroupId",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/skus")
  async updateSkus(
    @common.Param() params: SkuSubGroupIdWhereUniqueInput,
    @common.Body() body: SkuWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      skus: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "SkuSubGroupId",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/skus")
  async disconnectSkus(
    @common.Param() params: SkuSubGroupIdWhereUniqueInput,
    @common.Body() body: SkuWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      skus: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
