/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SkuPackageService } from "../skuPackage.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SkuPackageCreateInput } from "./SkuPackageCreateInput";
import { SkuPackageWhereInput } from "./SkuPackageWhereInput";
import { SkuPackageWhereUniqueInput } from "./SkuPackageWhereUniqueInput";
import { SkuPackageFindManyArgs } from "./SkuPackageFindManyArgs";
import { SkuPackageUpdateInput } from "./SkuPackageUpdateInput";
import { SkuPackage } from "./SkuPackage";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SkuPackageControllerBase {
  constructor(
    protected readonly service: SkuPackageService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "SkuPackage",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SkuPackage })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: SkuPackageCreateInput
  ): Promise<SkuPackage> {
    return await this.service.create({
      data: {
        ...data,

        inclusionSku: data.inclusionSku
          ? {
              connect: data.inclusionSku,
            }
          : undefined,

        sku: data.sku
          ? {
              connect: data.sku,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        inclusionSku: {
          select: {
            id: true,
          },
        },

        inclusionSkuPrice: true,

        sku: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "SkuPackage",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [SkuPackage] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(SkuPackageFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<SkuPackage[]> {
    const args = plainToClass(SkuPackageFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,

        inclusionSku: {
          select: {
            id: true,
          },
        },

        inclusionSkuPrice: true,

        sku: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "SkuPackage",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SkuPackage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: SkuPackageWhereUniqueInput
  ): Promise<SkuPackage | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,

        inclusionSku: {
          select: {
            id: true,
          },
        },

        inclusionSkuPrice: true,

        sku: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "SkuPackage",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SkuPackage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: SkuPackageWhereUniqueInput,
    @common.Body() data: SkuPackageUpdateInput
  ): Promise<SkuPackage | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          inclusionSku: data.inclusionSku
            ? {
                connect: data.inclusionSku,
              }
            : undefined,

          sku: data.sku
            ? {
                connect: data.sku,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          inclusionSku: {
            select: {
              id: true,
            },
          },

          inclusionSkuPrice: true,

          sku: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "SkuPackage",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SkuPackage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: SkuPackageWhereUniqueInput
  ): Promise<SkuPackage | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,

          inclusionSku: {
            select: {
              id: true,
            },
          },

          inclusionSkuPrice: true,

          sku: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
